### ISSUE TITLE
GPU out of memory 

### ISSUE THREAD

**Issue by ReyonRen** [facebookresearch/DPR#64]
Hi, thanks  for the cool work!

I try to train the reader using 
```
python src/train_reader.py \
--encoder_model_type hf_bert \
--seed 42 \
--learning_rate 1e-4 \
--eval_step 2000 \
--do_lower_case \
--eval_top_docs 50 \
--warmup_steps 0 \
--sequence_length 350 \
--batch_size 1 \
--passages_per_question 24 \
--num_train_epochs 3 \
--dev_batch_size 72 \
--passages_per_question_predict 50 \
--pretrained_model_cfg bert-base-uncased \
--train_file train.0.pkl \
--dev_file test.0.pkl \
--output_dir train_output
```
But even if I set the batch_size=1，the GPU will also out of memory...
I use single card of V100 16G GPU.
Can you help me? Any help will be appreciate!

**Comment by vlad-karpukhin** [comment]
Hi,
Your effective BERT encoder input is still 1x24(passages_per_question) = 24 sequences.
You can try to reduce passages_per_question but the quality will be worse most likely.

**Comment by ReyonRen** [comment]
Thank you for your nice reply!

I wonder if I use 8 * 16GB GPU with same config, the memort cost per GPU will decrease? Or equal to 1*16GB?

**Comment by vlad-karpukhin** [comment]
passages_per_question is defined per question regardless of how many gpus or which distributed mode you use.
batch_size setting is defined per GPU in DDP mode and per all available gpus in DP mode.
DP mode is enabled automatically if you don't run it with the torch distribute launcher tool and have more than 1 gpu available.
Please also note that you can't use batch_size=1 when using DP mode with multiple gpus.

**Comment by ReyonRen** [comment]
Thank you again for your nice reply!

I tried to use this setting in 8*32GB GPU:

```
/opt/conda/bin/python3 -m torch.distributed.launch --nproc_per_node=8 src/train_reader.py \
    --eval_top_docs 50 \
    --seed 42 \
    --learning_rate 1e-5 \
    --encoder_model_type hf_bert \
    --do_lower_case \
    --warmup_steps 0 \
    --batch_size 16 \
    --passages_per_question 24 \
    --eval_step 2000 \
    --pretrained_model_cfg bert-base-uncased \
    --output_dir output \
    --num_train_epochs 10000 \
    --dev_file ./test.0.pkl \
    --train_file ./train.0.pkl \
    --dev_batch_size 72 \
    --passages_per_question_predict 50 \
    --sequence_length 350 \
```
It seems like the recommended setting in README using `train.0.pkl` download from your script as training data, but I still suffered out of GPU memory problem. I wonder if I used some wrong setting? 

Thank you!

**Comment by vlad-karpukhin** [comment]
Hi Reyon,
Sorry I didn't mention earlier - we used train_reader in DP mode only(contrary to train_dense_retriever). So don't use  torch.distributed.launch.
Use this as a sample:
https://github.com/facebookresearch/DPR#5-reader-training

If you use that with 8*32GB GPU then it seems there is some clear cuda issue with you environment.

**Comment by ReyonRen** [comment]
@vlad-karpukhin  I have solved it. Thank you for your nice reply!
